package: mform
version: '3.2.0'
name: MForm
author: 'Joachim Doerr'
supportpage: www.redaxo.org/de/forum/

page:
  title: 'translate:title'
  perm: admin

requires:
  packages:
    textile: '~ 5.0 alpha'
