package: mform
version: '3.3.0'
name: MForm
author: 'Joachim Doerr'
supportpage: www.redaxo.org/de/forum/

load: late

page:
    title: 'translate:title'
    perm: admin[]
    subpages:
        info: { title: 'translate:info' }
        config: { title: 'translate:config' }
        demo: { title: 'translate:demo' }

requires:
  packages:
    textile: '~ 5.0 alpha'