package: mform
version: '4.2.2'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform

page:
    title: 'translate:title'
    perm: admin[]
    subpages:
        info: { title: 'translate:info' }
        config: { title: 'translate:config' }
        demo: { title: 'translate:demo' }
