package: mform
version: '5.0.0'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform

page:
    title: 'translate:title'
    perm: admin[]
    subpages:
        overview: { title: 'translate:overview' }
        demo: { title: 'translate:demo' }
