package: mform
version: '4.0.2'
name: MForm
author: 'Joachim Doerr'
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:title'
    perm: admin[]
    subpages:
        info: { title: 'translate:info' }
        config: { title: 'translate:config' }
        demo: { title: 'translate:demo' }

requires:
  packages:
    textile: '~ 2.0.0-beta2'
